-- Baseline: the schema exactly as Hibernate ddl-auto=update had grown it on the live deployment by
-- 2026-10-09, taken from pg_dump. Idempotent on purpose: it runs on every database, including one
-- that already carries these tables, because the Postgres schema is shared with device-api and so
-- "non-empty" tells Flyway nothing about whether OUR tables exist (see application.yml).
-- Constraint names are kept as Hibernate generated them so a later migration can refer to the same
-- name everywhere.

CREATE TABLE IF NOT EXISTS der_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    approved boolean,
    duration_seconds bigint NOT NULL,
    energize boolean,
    export_limitw double precision,
    import_limitw double precision,
    interval_start timestamp(6) with time zone NOT NULL,
    mrid character varying(255) NOT NULL,
    raw_payload text NOT NULL,
    received_at timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    submitted_by_lfdi character varying(255) NOT NULL,
    target_active_powerw double precision,
    program character varying(255) NOT NULL,
    CONSTRAINT der_event_pkey PRIMARY KEY (id),
    CONSTRAINT ukpj4led1lbxae3hf6mq006lmst UNIQUE (mrid),
    CONSTRAINT der_event_program_check CHECK (program IN ('DLR_LINE_CONSTRAINT', 'ERCOT_FLEX')),
    CONSTRAINT der_event_status_check
        CHECK (status IN ('SCHEDULED', 'ACTIVE', 'CANCELLED', 'SUPERSEDED', 'COMPLETED'))
);

CREATE TABLE IF NOT EXISTS dispatch_settings (
    id bigint NOT NULL,
    mode character varying(255) NOT NULL,
    operator_reserve_wh double precision,
    CONSTRAINT dispatch_settings_pkey PRIMARY KEY (id),
    CONSTRAINT dispatch_settings_mode_check CHECK (mode IN ('AUTO', 'MANUAL'))
);
