-- The site's operational history: one row per thing that happened, written by the code path
-- that made it happen. Events are not alarms: nothing here is acknowledged (alarms get their own
-- store with a lifecycle). subject is the mRID for DER events, or the setting name otherwise;
-- the typed columns after it are each filled only where the type gives them a meaning.
CREATE TABLE IF NOT EXISTS event_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred_at timestamp(6) with time zone NOT NULL,
    type varchar(255) NOT NULL,
    subject varchar(255) NOT NULL,
    actor varchar(255),
    program varchar(255),
    status varchar(255),
    state varchar(255),
    value double precision,
    detail varchar(255),
    CONSTRAINT event_log_pkey PRIMARY KEY (id),
    CONSTRAINT event_log_type_check CHECK (type IN ('DER_EVENT_RECEIVED', 'DER_EVENT_UPDATED',
        'DER_EVENT_STATE', 'DER_EVENT_APPROVED', 'DER_EVENT_REJECTED', 'OPERATOR_RESERVE_SET',
        'DISPATCH_MODE_SET')),
    CONSTRAINT event_log_program_check CHECK (program IN ('DLR_LINE_CONSTRAINT', 'ERCOT_FLEX')),
    CONSTRAINT event_log_status_check CHECK (status IN ('SCHEDULED', 'ACTIVE', 'CANCELLED',
        'SUPERSEDED', 'COMPLETED')),
    CONSTRAINT event_log_state_check CHECK (state IN ('IDLE', 'PENDING', 'ARMED', 'ACTIVE',
        'REJECTED'))
);
-- the HMI reads "everything since t"; the state recorder reads "the last state row for this mRID".
CREATE INDEX IF NOT EXISTS event_log_occurred_at_idx ON event_log (occurred_at);
CREATE INDEX IF NOT EXISTS event_log_subject_type_idx ON event_log (subject, type, occurred_at);
